CMakeLists.txt

drop cmake requirement to 3.9

---

include/camp/camp.hpp
include/camp/make_unique.hpp

As discussed, adding a make_unique to camp for use in other projects

Add make_unique

---

include/camp/tuple.hpp
test/resource.cpp

@rhornung67, this should address the warning issue and clean up some other small issues in the same area.

Kill eq warning

---

include/camp/resource/omp_target.hpp

Also fixes errors reported over in RAJA  #LLNL/RAJA#801.

Register singleton and fix device_pointer issue in memset

---

include/camp/tuple.hpp

Fix camp invoke by adding decay to TupleLike when getting tuple_size

Fix camp invoke

---

include/camp/helpers.hpp

Allows use of removal and adding of * and ** to types.

Add pointer rem & add helper.

---

CMakeLists.txt
include/camp/defines.hpp
include/camp/resource.hpp
include/camp/resource/sycl.hpp

Initial PR to add a SYCL resource.

SYCL Resource

---

include/camp/helpers.hpp

Simple implementations of some new helpers for camp.  I'm going to add in a bit more in this vein, but the lack of these was causing issues for some reduction work, so these are going up sooner.

add CAMP_EXPAND and for_each_arg

---

include/camp/defines.hpp
include/camp/resource/cuda.hpp
include/camp/resource/hip.hpp

Add error checking to cuda and hip calls and throw an exception when there is a cuda error. The creation of the error string is not very elegant, suggestions?

Add error checking to cuda and hip calls

---

include/camp/resource.hpp
include/camp/resource/cuda.hpp
include/camp/resource/hip.hpp
include/camp/resource/host.hpp
include/camp/resource/omp_target.hpp
include/camp/resource/sycl.hpp
test/resource.cpp

Event Proxy stores the internal resource by value. 
This is in relation to https://github.com/LLNL/RAJA/pull/1054

EventProxy stores resource by value.

---

include/camp/resource/hip.hpp

This PR adds device and memory size guards to mirror the functionality of Cuda resource. The size guards on memory operations are needed to get some failing tests to work in RAJA.

Hip resource device guards.

---

include/camp/resource/cuda.hpp
include/camp/resource/hip.hpp
test/resource.cpp

Move private hip/cuda constructor to public

---

include/camp/defines.hpp
include/camp/resource/cuda.hpp
include/camp/resource/hip.hpp
test/resource.cpp

Fix the CudaEvent and HipEvent constructor taking a Cuda or Hip resource.

Fix Cuda and Hip Event constructor

---

include/camp/resource/event.hpp

Fixes the Umpire issue mentioned via email.

Add copy/move assign to Event

---

.gitmodules
CMakeLists.txt
Dockerfile
azure-pipelines.yml
cmake/load_blt.cmake
scripts/gen-header-list.sh
scripts/get-deps.sh
scripts/get-llvm.sh
scripts/travis_build_and_test.sh
test/CMakeLists.txt
test/tuple_out_of_range.cpp

This adds azure CI support, along with a new docker file in the style of the one from RAJA but with a bit of special buildkit sauce to deduplicate much of it and allow testing directly from various upstream containers rather than maintaining our own layers on them manually.  I'd really like to get this in, and get CI required.  Would be great to have gitlab support in here as well if we can work that out.

switch to azure CI

---

include/camp/resource/cuda.hpp

avoid nvcc no return warning

---

CMakeLists.txt
cmake/campConfig.cmake.in
cmake/load_blt.cmake

Changes from llnl/raja#1284 for camp.

Protect exports

---

include/camp/helpers.hpp
test/tuple.cpp

Fix warnings in tuple test added in previous PR.

Quiet uninitialized var warnings

---

include/camp/resource/hip.hpp

Include vector in hip resource header.

Fix an include

---

include/camp/resource.hpp
include/camp/resource/cuda.hpp
include/camp/resource/hip.hpp
include/camp/resource/host.hpp
include/camp/resource/omp_target.hpp
include/camp/resource/sycl.hpp
test/resource.cpp

There may not be many things you can do with a const resource but getting the platform seems reasonable.

Make get_platform a const method

---

azure-pipelines.yml
include/camp/resource/omp_target.hpp
include/camp/resource/sycl.hpp
test/resource.cpp

Generalize resource tests and test all resource types.

Add tests for Sycl resource and more for Omp resource

---

include/camp/resource/omp_target.hpp

Remove extra include in resource/omp_target.hpp

Remove extra include
