- test/CMakeLists.txt
I haven't tested this on blueos as yet, but I think the issue is a combination of new cmake with cuda enabled.  Doing the set there makes the variable exist before the option is created, this should fix it.
> set after gtest defines option to avoid CMP0077

- CMakeLists.txt
@trws when we make a tarfile for the release using the script make_release_tarball.sh in RAJA/scripts, the contents of the camp/extern/googletest directory are missing. As a result, when users try to configure RAJA with ENABLE_TESTS=Off, Cmake fails. See 
https://github.com/LLNL/RAJA/issues/684. This PR is one potential fix. If you see a better way to do this, or a way to modify the 'make tarball' script in RAJA, I'm amenable to that.
> Resolve issue when RAJA is built with ENABLE_TESTS=Off

- include/camp/resource.hpp
- include/camp/resource/cuda.hpp
- include/camp/resource/event.hpp
- include/camp/resource/hip.hpp
- include/camp/resource/host.hpp
- include/camp/resource/platform.hpp
Renaming context.hpp to resource.hpp to match namespace name.
Adds the copyright information to all of the resource files.
> Renaming context.hpp to resource.hpp

- include/camp/defines.hpp
- include/camp/tuple.hpp
The cuda model requires you not to have host/device notations on
defaulted constructors.  Apparently hip requires them to generate the
constructors on the device.  This commit adds a new macro so we can get
host/device only for HIP, and uses it to annotate defaulted constructors
on tuple_helper.
> add __host__ __device__ to defaulted hip constructors

- CMakeLists.txt
- include/camp/defines.hpp
- include/camp/resource.hpp
- include/camp/resource/cuda.hpp
- include/camp/resource/event.hpp
- include/camp/resource/hip.hpp
- include/camp/resource/host.hpp
- include/camp/resource/omp_target.hpp
- include/camp/resource/platform.hpp
- test/CMakeLists.txt
- test/resource.cpp
This is a collection of fixes to prepare the Resource types to be used as part of a generic allocation mechanism, and includes a helper (based heavily on what you were starting with @davidbeckingsale) for getting a resource type based on the platform value.
This should be enough to get going with to unify the cuda and hip paths of stuff.  There's some more to be done for me to consider this really "finished" though.
1. [ ] We don't have error handling or propagation on memcpy/memset in these, need a good way to handle it
2. [ ] Platform is weirding me out, we have enough to differentiate for the memory platforms for host cuda and hip, but resources need to work for TBB and openmp, and openmp offload too for that matter.  I think we may need to be able to differentiate between execution …
> Resource preparation

- include/camp/defines.hpp
Some builds (gcc <= 5?) in CHAI are failing because of the 'depend' and 'nowait' clauses in omp_targets.hpp . I think those are 4.5 features? Updating to this seems to fix those builds.
> Detecting OMP 4.5 for CAMP_HAVE_OMP_OFFLOAD def

- include/camp/resource/host.hpp
Host resource memcpy hangs when called. Defining namespace fixes this.
> Host memcpy call changed to std::memcpy to avoid hanging.

- include/camp/defines.hpp
Clang-cuda does not support the pragma used by nvcc to suppress host device warnings, don't use it with clang-cuda.
> Fix clang-cuda warnings from CAMP_SUPPRESS_HD_WARN

- include/camp/camp.hpp
- test/accumulate.cpp
First cut at support for cartesian product operation on camp lists.  The join operation is likely to be rather slow right now, but the interface should be stable.
> add list join and product helpers

- include/camp/resource/hip.hpp
Since ``hip_event`` is a pointer we require the ``->`` operator
> Bugfix for hip_event

- include/camp/resource.hpp
- test/resource.cpp
We apparently had two bugs here, both caught by @rhornung67 with a new
case we somehow hadn't hit before.
1. The internal context was sometimes being constructed with a reference
type when it should have been the bare type
2. The rvalue-reference constructor was being used even for copy
construction, which made Resource try and wrap an already erased
Resource.
Both of these were preventing copying and storing a Resource by value.
This should fix both issues, and adds a minimal test to ensure we don't
regress.
@rhornung67, any chance you could test this and see if it lets you work the way you want? The intention is these should be (relatively) cheaply copyable.  We may optimize out the shared_ptr to help that at some point but it's a convenient way to start out.
> resource: fix copy construction bug

- include/camp/defines.hpp
- include/camp/helpers.hpp
CAMP_ALLOW_UNUSED_LOCAL was still returning unused variable warnings when compiling with cuda, this seems to hush nvcc up.
> Fixing unused var warning on nvcc

- appveyor.yml
- include/camp/camp.hpp
- include/camp/defines.hpp
- include/camp/helpers.hpp
- include/camp/resource/cuda.hpp
- include/camp/tuple.hpp
- test/CMakeLists.txt
- test/tuple.cpp
@rrsettgast noted in GEOSX/GEOSX#866 that we're missing a way to use `invoke` on a tuple with a constructor, C++17 includes `make_from_tuple` for this use case, and I can't think of a reason not to provide it for us as well.
> Add C++17 make_from_tuple for camp tuple

- include/camp/tuple.hpp
The hipcc workarounds from before 3.5 break 3.5.  This gets hip working again, and improves build times on there as well, but means we *require* hip 3.5.  Upside is there is now absolutely no hip specific code in the tuple, which is kinda awesome.
@MrBurmark, @rhornung67
> Remove hip workarounds

- include/camp/defines.hpp
- include/camp/list/at.hpp
- include/camp/number.hpp
Incorporate more checks for integer sequence building intrinsics.  This makes explicit a number of checks for nvcc, icpc, xl, msvc and pgi so we get intrinsics working in as many places as possible for sequence building and pack element selection for `at<>`.
The libstdc++ and libc++ libraries use these at newer versions as well, so we could consider using these checks and deferring to the native `std::make_integer_sequence` in the future.  I'm vaguely for keeping the setup as-is, if only because it makes it easier for us to ensure we get a reasonably fast implementation everywhere.
> Faster sequences

- CMakeLists.txt
The "ENABLE_TESTS" option is named too generically which leads to
name collisions when camp is used a sub-module within another
project. As a result, the CAMP tests will always be run with
the tests of the super-project, which may be using the same
option. Notably, BLT has also an option "ENABLE_TESTS", so
any BLT project that uses camp as a submodule will run into this.
This commit renames this option in order to give parent projects
more fine-grain control of whether to build CAMP's tests or not.
> Add "CAMP_" prefix to "ENABLE_TESTS" option

- include/camp/defines.hpp
The compiler defines need to match between including this header and where the `cudaError_t` type is used below.  This fixes the following error:
```
[  6%] Building CXX object src/umpire/resource/CMakeFiles/umpire_resource.dir/MemoryResource.cpp.o
cd spack-stage-umpire-5.0.1-effmrh5m4m5c2vxd6cdtos3zbrkhymz3/spack-build-effmrh5/src/umpire/resource && /usr/WS2/white238/serac/libs/blueos_3_ppc64le_ib_p9/2021_06_24_15_13_34/spack/lib/spack/env/clang/clang++ -DCAMP_HAVE_CUDA -Icamp-0.1.0serac/include -I/usr/tce/packages/cuda/cuda-11.2.0/include -Ispack-stage-umpire-5.0.1-effmrh5m4m5c2vxd6cdtos3zbrkhymz3/spack-src/src -Ispack-stage-umpire-5.0.1-effmrh5m4m5c2vxd6cdtos3zbrkhymz3/spack-build-effmrh5/include -Wpedantic       -Wall -Wextra  -O2 -g -DNDEBUG -fPIC -std=c++11 -o …
```
> Compiler define mismatch

- include/camp/defines.hpp
This seems to be causing some TOSS3-gcc6 failures in RAJA https://github.com/LLNL/RAJA/pull/930. GCC-6.1.0 has an advanced enough OpenMP version which turns on omp-target in CAMP. This problem correctly manifests itself as compilation errors when run manually. However, Travis compiles successfully but segfaults at runtime, which I'm not sure why.
> Making sure omp target is not compiled on TOSS, assuming no GPUs.

- include/camp/resource.hpp
Since we pass back a erased resource type in https://github.com/LLNL/RAJA/pull/1029, we need to add get_event_erased method class to the resource class.
> add get_event_erased to resource class

- include/camp/resource.hpp
- test/resource.cpp
Fixes #49
Adds the link through for the wait method in the type erased version of
Resource.
> add wait method to type-erased Resource

- include/camp/resource/sycl.hpp
Changing SYCL resources to use in order queue property to ensure expected functionality.
> SYCL Resource - In order queue

- .gitignore
- include/camp/resource.hpp
- include/camp/resource/event.hpp
- test/CMakeLists.txt
- test/resource.cpp
Fixes #51
Add support for getting the native event type out of EventProxy.
This is now the default, with Event fixed to allow implicit conversion
from native event types and a new `operator Event()` overload on
EventProxy all tests pass in tree, need to see how this impacts codes.
> add support for native events from EventProxy

- include/camp/resource/cuda.hpp
- include/camp/resource/hip.hpp
Do not change device if the requested device is already in use.
This let's us avoid overheads especially during profiling as these are
used frequently.
> Only change device if necessary in device guards

- include/camp/resource.hpp
- include/camp/resource/cuda.hpp
- include/camp/resource/hip.hpp
- include/camp/resource/host.hpp
- include/camp/resource/omp_target.hpp
- include/camp/resource/platform.hpp
- include/camp/resource/sycl.hpp
@rhornung67
Here's my first cut at adding different allocation types to the resources.  I decided to start it off as an argument that's defaulted to device, but if we want them to be separate functions that's an option.  There are three modes, device, pinned, and managed currently.  I'm tempted to make it device, *shared* and managed so that it's based on the access semantics of the memory rather than the location, but most people aren't used to that (it's what we've been working on for OpenMP, pinned and true shared can provide the same stronger guarantee than managed can, but on cuda, sycl and hip both shared and managed are accessed through the same function).
One aspect I'm not terribly fond of is having to pass the access type to the free as well.  While SYCL doesn't need it, and …
> add memory access type to allocation routines

- include/camp/defines.hpp
- test/resource.cpp
Needed for older gcc's in RAJA tests.
> Specify unused vars in resource test for old gccs.

- include/camp/defines.hpp
Adds missing include needed for cuda and hip asserts.
> Add stdexcept include to camp defines

- include/camp/resource.hpp
Change the EventProxy copy constructor signature to const& to avoid a warning from the intel compiler.
> Fix warning in EventProxy copy constructor

- CMakeLists.txt
Use the runtime variants since we don't actually use compiler features in camp itself for these things.
> change offload deps to use the _runtime variants

- .gitignore
- CMakeLists.txt
- Dockerfile
- azure-pipelines.yml
- include/camp/camp.hpp
- include/camp/defines.in.hpp
- include/camp/helpers.hpp
- include/camp/resource/cuda.hpp
- include/camp/resource/hip.hpp
- include/camp/resource/omp_target.hpp
- include/camp/resource/sycl.hpp
- include/camp/tuple.hpp
- scripts/get-deps.sh
- test/CMakeLists.txt
Basically what the title says.
This will make camp require c++14.  Current changes are as follows:
* require nvcc 10+ since 9 didn't support 14 at all 
* remove workarounds from nvcc9 since there were many
* rework CAMP_HAVE_{backend} to be activated based on compiler and configuration, add new CAMP_ENABLE_{backend} defines to be configured by cmake, essentially the HAVE macros now work much like the RAJA_ACTIVE_{backend} macros
* remove trailing return types where they are redundant
* rework tuple indexing to remove issues with trailing return type removal
Before this merges, I would like to rework the tested compiler list here to match the bottom we will support on each platform.  I'd propose the following, but need guidance on versions people care about, especially for the proprietary …
> c++14 at last

- include/camp/tuple.hpp
While the `test-kernel-single-loop-ForICount-8-OpenMPTarget` test in RAJA (https://github.com/LLNL/RAJA/pull/1207), there was a compilation error in CAMP tuple. I'm not sure if this is the right solution, but making the base tuple_helper class publicly accessible solved the build error (although the test still failed with XLC).
Note: This solution does not solve the clang internal error https://github.com/LLNL/RAJA/issues/1216.
Error:
In file included from /usr/WS1/chen59/allraja/rajaatomicexhaustive/raja_git_atomicexhaustive/build_lc_blueos-xl_omptarget-2021.12.22/test/functional/kernel/single-loop-tile-icount-tcount/test-kernel-single-loop-ForICount-8-OpenMPTarget.cpp:11:
In file included from /usr/WS1/chen59/allraja/rajaatomicexhaustive/raja_git_atomicexhaustive/test/include/RAJA_test-b …
> Make tuple base public.

- cmake/load_blt.cmake
Also make sure check for whether BLT is loaded is in the right spot
when camp is a submodule in a project that is a submodule of another project.
Note: that the removed code is not wrong, technically. However, what is in this PR is consistent with our other projects that use BLT.
> Remove block of BLT check logic (redundant with block below)

- .gitignore
- include/camp/tuple.hpp
- test/tuple.cpp
These are features of c++17 that make using tuples much easier.
Class template argument deduction allows the following shorthand:
`camp::tuple t{1, 2.0};`
Contribution from Sam Mish (@samuelpmishLLNL)
Structured binding also allows some shorthand:
`auto [a, b] = t;`
Contribution from Jon Wong (@jonwong12)
> Support CTAD and structured bindings with tuple

- include/camp/helpers.hpp
Fix warning caused by CAMP_EXPAND by naming and "sinking" the array.
Fixes #115 .
> Fix warning caused by CAMP_EXPAND

- include/camp/helpers.hpp
Avoid naming array in CAMP_EXPAND so it is more compatible with existing code. This should avoid causing errors is EXPAND is used multiple times in the same scope.
@mcfadden8 found that the previous change broke umpire as umpire passed the result to a sink like function to quiet the warning. This change will still break umpire as sink returns void, but its fixed here https://github.com/LLNL/Umpire/pull/786#pullrequestreview-1133512641.
> Avoid naming array in CAMP_EXPAND

- include/camp/tuple.hpp
- test/tuple.cpp
Here is my attempt to add support for rvalue forms of get with tuple.
This fixes #116.
> Add rvalue get for tuples

- CMakeLists.txt
- include/camp/config.in.hpp
- include/camp/defines.hpp
- include/camp/resource.hpp
- include/camp/resource/cuda.hpp
- include/camp/resource/hip.hpp
- include/camp/resource/host.hpp
- include/camp/resource/omp_target.hpp
- include/camp/resource/sycl.hpp
- src/errors.cpp
- test/resource.cpp
Use whatever is the current device in hip and cuda resources instead of using device 0.
Fix race conditions in the Cuda, Hip, and Sycl resource get stream and queue methods.
This is aimed at fixing this umpire issue https://github.com/LLNL/Umpire/issues/798 from @gzagaris.
> Use current GPU instead of device 0

- include/camp/tuple.hpp
- test/tuple.cpp
This small PR fixes an issue I encountered when playing around implementing some algorithms on tuples (`zip` in particular).
When attempting to construct a `tuple<tuple<A,B>>` from a single argument of type `tuple<A,B> &&`, the converting constructor overload is chosen instead of direct constructor (using the terminology of [std::tuple](https://en.cppreference.com/w/cpp/utility/tuple/tuple) constructors).
This results in the error
```
In file included from /home/klevtsov/work/camp/include/camp/camp.hpp:24,
from /home/klevtsov/work/camp/test/tuple.cpp:18:
/home/klevtsov/work/camp/include/camp/tuple.hpp: In instantiation of ‘constexpr camp::internal::tuple_helper<camp::int_seq<long int, Indices ...>, camp::list<Args ...> >::tuple_helper(Args&& ...) [with Args = {A&}; Types = {A, B}; long …
```
> Restrict tuple's converting constructor

- include/camp/tuple.hpp
- test/tuple.cpp
> Allow for structured bindings from const camp::tuple

- cmake/campConfig.cmake.in
- cmake/load_blt.cmake
BLT has a new macro `blt_install_tpl_setups` that will install files such as `BLTSetupOpenMP.cmake` etc to enable configuration of TPL targets at the build time.  For example, if camp uses CUDA, a repo linking to camp can re-evaluate the compile and link flags inside `BLTSetupCUDA.cmake` at configuration time, correcting possible errors caused by incorrect link flags, etc.  
This PR moves the BLT commit to include this macro, and updates camp's cmake to use the new macro.
> Update BLT and change BLT TPL configuration to use new macro

- Dockerfile
- scripts/get-deps.sh
The tricks we were using to avoid having to download a few GB extra for every oneapi test stopped working.  Revert this to the simpler usage.
> Fix oneapi in ci

- include/camp/tuple.hpp
When I was compiling camp with gcc12, I get the several of the following types of errors:
```
In file included from /usr/workspace/settgast/Codes/geosx/Shiva/tpl/camp/include/camp/camp.hpp:24,
from /usr/workspace/settgast/Codes/geosx/Shiva/src/common/types.hpp:12,
from /usr/workspace/settgast/Codes/geosx/Shiva/src/discretizations/unitTests/testLagrangeBasis.cpp:6:
/usr/workspace/settgast/Codes/geosx/Shiva/tpl/camp/include/camp/tuple.hpp: In function ‘constexpr camp::tuple_element_t<index, camp::tuple<Types ...> >& camp::get(const tuple<Types ...>&)’:
/usr/workspace/settgast/Codes/geosx/Shiva/tpl/camp/include/camp/tuple.hpp:440:29: error: declaration of ‘t’ shadows a global declaration [-Werror=shadow]
440 | get(const tuple<Types...>&  t) noexcept
|     ~~~~~~~~~~~~~~~~~~~~~~~~^
In file …
```
> Avoid some -Wshadow warnings in gcc12

- include/camp/resource/hip.hpp
- In ROCm6.0 hipPointerAttribute_t.memoryType will be removed from HIP.
- Instead hipPointerAttribute_t.type to be used.
- This is causing build failure for RAJAPerf
> use hipPointerAttribute_t.type as HIP is removing hipPointerAttribute_t.memoryType

- include/camp/resource/sycl.hpp
Change to new SYCL API with callable `gpu_selector_v`.
Related to RAJA update https://github.com/LLNL/RAJA/pull/1619.
> Draft: SYCL Warnings

- include/camp/array.hpp
- include/camp/tuple.hpp
- test/array.cpp
There's no reason to not supply them before 17.
They can still be used in code for generic tuple-like classes.
> Allow std tuple_size and tuple_element before C++17

- test/array.cpp
The tests that I allowed to run with c++14 had some things that required c++17. Not sure why I was able to merge if the tests didn't compile.
> Fix array test with c++14

- include/camp/resource/omp_target.hpp
Add accessors for dev and addr to Omp resource so they can be used in RAJA and RAJAPerf. Currently RAJA always uses the default device and ignores the resource.
> Add accessors for dev and addr to Omp resource

- include/camp/helpers.hpp
Clamp the value to be at most the size of the string_view to avoid UB.
> Fix call to remove_prefix
